### ISSUE TITLE
setting up Truststore and keystore

### ISSUE THREAD

**Issue by bb245** [eBay/parallec-samples#4]
Hi, This is great and was looking for something like this for sometime now.

I was trying to execute https calls using parallec package. Is there is a way where i can refer to keystore and truststore path/passwords to make https POST calls? Thanks.

**Comment by jeffpeiyt** [comment]
Hi @bb245 thanks for trying parallec out.

Could you refer [here](http://www.parallec.io/docs/api-overview/) for a POST example?  Could you please  elaborate more on which password you are referring to?  the truststore/keystore are normally used for HTTPS (e.g. Client auth) , please check examples [here](https://github.com/eBay/parallec-plugins/blob/master/parallec-clientauth/src/main/java/io/parallec/plugin/http/clientauth/ClientAuthAdaptor.java)

thanks,

**Comment by jeffpeiyt** [comment]
close the issue as there is no further activity
