### ISSUE TITLE
As a server?

### ISSUE THREAD

**Issue by renderit** [eBay/parallec-samples#5]
Great work with this! Wanted to know if it can be used on the server side to handle requests too? Or is it only be used as a client, sending gets and posts requests? 
I'm trying to make a server capable of handling massive amounts of post requests coming in! Any suggestions?

**Comment by jeffpeiyt** [comment]
Thanks @renderit for your interests. I feel Parallec is more for a client. At server side parallec will still be a client if your request handling logic internally need to open new request to other server.

Have you considered just using Async IO web server such as Netty? http://programmers.stackexchange.com/questions/112818/are-there-any-non-blocking-web-servers-for-java

**Comment by renderit** [comment]
@jeffpeiyt Right! Sure.. I din't know facebook is using tornado.. I heard node js itself is capable of handle 4 times that of tornado, since it complies down to assembly code. Hm thanks, if there are any other recommendations, let me know :) Thanks

**Comment by jeffpeiyt** [comment]
close the issue as there is no further activity
